# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Y32
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Y32. Chaotic (mostly) evil.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sledgang.github.io/" # the base hostname & protocol for your site
future: true
# Social
githubUsername: y32

# Define the authors here, along the format
authors:
  aria:
    name: aria
    real_name: Aria Edmonds
    discord_discrim: 9888
    github: snorflake
  cyan:
    name: Cyan
    discord_discrim: '0340'
    github: cyan101
  echo:
    name: Echo
    discord_discrim: 5248
    github: LeggoMyEcho
  ghosty:
    name: Ghosty
    real_name: Andrew Austin
    discord_discrim: 8204
    github: TrenchFroast
  nekka:
    name: NekkaLucifer
    real_name: Daniel Worrall
    discord_discrim: 9620
    github: daniel-worrall
  nymous:
    name: Nymous
    real_name: Thomas Gaudin
    discord_discrim: 4859
    github: nymous
  snapcase:
    name: snapcase
    discord_discrim: 8712
    github: snapcase
  unleashy:
    name: Unleashy
    real_name: Eduardo Fernandes
    discord_discrim: 9254
    github: unleashy
  z64:
    name: z64
    real_name: Zac Nowicki
    discord_discrim: 2639
    github: z64
  pixel:
    name: PixeL
    discord_discrim: 7065
    github: pixelinc

# Build settings
markdown: kramdown

themeColor: blue #purple # green, blue, orange, purple, grey
fixedNav: 'true' # true or false

permalink: /:year/:month/:title
markdown: kramdown
include: [_pages]
exclude: [_site, CHANGELOG.md, LICENSE, README.md, vendor]
sass:
  style: compressed
